from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List
import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from ..contract import Generator, GeneratorSpec, Requirement, register_generator


@register_generator
class PaidSocialReportGenerator(Generator):
    """
    Deliverable: paid_social_report (v1.0.0)
    Generates monthly paid media performance reporting across ad channels.
    """
    spec = GeneratorSpec(
        name="paid_social_report",
        version="1.0.0",
        requires=(
            Requirement(
                domain="paid",
                min_version="paid_v2",
                columns=("spend", "impressions", "reach", "clicks", "engagements", "conversions")
            ),
        ),
        outputs=("xlsx",),
        blocking_checks=("rate_over_100", "vs_platform_totals"),
        uses_narrative=False,
    )

    def build(self, brand: Dict[str, Any], period: str, data: Dict[str, Any], out_dir: str | Path) -> List[str]:
        paid_rows = data.get("paid", [])
        identity = brand.get("identity", {})
        display_name = identity.get("display_name", "Brand")
        palette = identity.get("palette", ["1C2321", "4E8C2B"])

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Paid Performance"

        header_fill = PatternFill(start_color=palette[0].replace("#", ""), end_color=palette[0].replace("#", ""), fill_type="solid")
        font_header = Font(name="Arial", size=11, bold=True, color="FFFFFF")
        font_title = Font(name="Arial", size=14, bold=True, color="1C2321")

        ws["A1"] = f"{display_name} - Paid Social Performance Report"
        ws["A1"].font = font_title
        ws["A2"] = f"Period: {period} | Generated by HOWL Platform"

        headers = ["Date", "Channel", "Campaign", "Spend (INR)", "Impressions", "Clicks", "Engagements", "Conversions"]
        for col_idx, h in enumerate(headers, start=1):
            cell = ws.cell(row=4, column=col_idx, value=h)
            cell.fill = header_fill
            cell.font = font_header

        out_path = Path(out_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        final_file = out_path / f"{display_name.lower()}_paid_social_{period}.xlsx"
        wb.save(final_file)
        return [str(final_file.resolve())]
