from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List
import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from ..contract import Generator, GeneratorSpec, Requirement, register_generator


@register_generator
class PaidSocialReportGenerator(Generator):
    """
    Deliverable: paid_social_report (v1.0.0)
    Generates branded Excel (.xlsx) report from canonical_paid data.
    """
    spec = GeneratorSpec(
        name="paid_social_report",
        version="1.0.0",
        requires=(
            Requirement(
                domain="paid",
                min_version="paid_v2",
                columns=("spend", "impressions", "reach", "clicks", "engagements", "conversions")
            ),
        ),
        outputs=("xlsx",),
        blocking_checks=("rate_over_100", "vs_platform_totals"),
        uses_narrative=False,
    )

    def build(self, brand: Dict[str, Any], period: str, data: Dict[str, Any], out_dir: str | Path) -> List[str]:
        paid_rows = data.get("paid", [])
        if not paid_rows:
            raise ValueError(f"No paid social data available for brand '{brand.get('brand_id')}' in period '{period}'.")

        # 1. Styling
        identity = brand.get("identity", {})
        display_name = identity.get("display_name", "Brand")
        palette = identity.get("palette", ["1C2321", "4E8C2B"])
        primary_hex = palette[0].replace("#", "")
        accent_hex = palette[1].replace("#", "") if len(palette) > 1 else "4E8C2B"

        header_fill = PatternFill(start_color=primary_hex, end_color=primary_hex, fill_type="solid")
        light_gray_fill = PatternFill(start_color="F4F6F5", end_color="F4F6F5", fill_type="solid")

        font_header = Font(name="Arial", size=11, bold=True, color="FFFFFF")
        font_title = Font(name="Arial", size=14, bold=True, color="1C2321")
        font_subtitle = Font(name="Arial", size=10, italic=True, color="555555")
        font_bold = Font(name="Arial", size=10, bold=True)
        font_regular = Font(name="Arial", size=10)

        thin_side = Side(border_style="thin", color="CCCCCC")
        thin_border = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)
        align_left = Alignment(horizontal="left", vertical="center")
        align_right = Alignment(horizontal="right", vertical="center")
        align_center = Alignment(horizontal="center", vertical="center")

        wb = openpyxl.Workbook()
        wb.remove(wb.active)

        # Totals
        tot_spend = sum(getattr(r, "spend", 0.0) for r in paid_rows)
        tot_imps = sum(getattr(r, "impressions", 0) for r in paid_rows)
        tot_reach = sum(getattr(r, "reach", 0) or 0 for r in paid_rows)
        tot_clicks = sum(getattr(r, "clicks", 0) for r in paid_rows)
        tot_engagements = sum(getattr(r, "engagements", 0) or 0 for r in paid_rows)
        tot_conv = sum(getattr(r, "conversions", 0.0) or 0.0 for r in paid_rows)

        ctr = (tot_clicks / tot_imps) if tot_imps > 0 else 0.0
        cpc = (tot_spend / tot_clicks) if tot_clicks > 0 else 0.0
        cpm = (tot_spend / tot_imps * 1000) if tot_imps > 0 else 0.0
        cpa = (tot_spend / tot_conv) if tot_conv > 0 else 0.0

        # ==============================================================
        # TAB 1: Summary
        # ==============================================================
        ws_sum = wb.create_sheet(title="Summary")
        ws_sum.views.sheetView[0].showGridLines = True

        ws_sum["A1"] = f"{display_name} - Paid Social Performance Dashboard"
        ws_sum["A1"].font = font_title
        ws_sum["A2"] = f"Reporting Period: {period} | Generated by HOWL Platform v{self.spec.version}"
        ws_sum["A2"].font = font_subtitle

        # KPI Cards (Row 4-5)
        kpi_headers = ["Total Spend (INR)", "Impressions", "Clicks", "CTR", "CPC (INR)", "CPM (INR)", "Engagements", "Conversions"]
        kpi_values = [
            f"₹{tot_spend:,.2f}",
            f"{tot_imps:,}",
            f"{tot_clicks:,}",
            f"{ctr * 100:.2f}%",
            f"₹{cpc:.2f}",
            f"₹{cpm:.2f}",
            f"{tot_engagements:,}",
            f"{int(tot_conv)}"
        ]

        for col_idx, (kh, kv) in enumerate(zip(kpi_headers, kpi_values), start=1):
            c_header = ws_sum.cell(row=4, column=col_idx, value=kh)
            c_header.fill = header_fill
            c_header.font = font_header
            c_header.alignment = align_center

            c_val = ws_sum.cell(row=5, column=col_idx, value=kv)
            c_val.font = Font(name="Arial", size=12, bold=True, color="1C2321")
            c_val.alignment = align_center
            c_val.fill = light_gray_fill
            c_val.border = thin_border

        # Campaign Summary Table (Row 8+)
        ws_sum["A7"] = "Campaign Performance Breakdown"
        ws_sum["A7"].font = font_bold

        camp_headers = ["Campaign", "Spend (INR)", "Impressions", "Clicks", "CTR", "CPC (INR)", "CPM (INR)", "Engagements", "Conversions"]
        for c_idx, h in enumerate(camp_headers, start=1):
            cell = ws_sum.cell(row=8, column=c_idx, value=h)
            cell.fill = header_fill
            cell.font = font_header
            cell.alignment = align_center

        # Group by campaign
        campaigns_map: Dict[str, List[Any]] = {}
        for r in paid_rows:
            campaigns_map.setdefault(getattr(r, "campaign", "Unnamed"), []).append(r)

        sorted_camps = sorted(
            campaigns_map.items(),
            key=lambda item: sum(getattr(r, "spend", 0.0) for r in item[1]),
            reverse=True
        )

        for c_idx, (c_name, c_rows) in enumerate(sorted_camps, start=9):
            c_spend = sum(getattr(r, "spend", 0.0) for r in c_rows)
            c_imps = sum(getattr(r, "impressions", 0) for r in c_rows)
            c_clks = sum(getattr(r, "clicks", 0) for r in c_rows)
            c_eng = sum(getattr(r, "engagements", 0) or 0 for r in c_rows)
            c_conv = sum(getattr(r, "conversions", 0.0) or 0.0 for r in c_rows)
            c_ctr = (c_clks / c_imps) if c_imps > 0 else 0.0
            c_cpc = (c_spend / c_clks) if c_clks > 0 else 0.0
            c_cpm = (c_spend / c_imps * 1000) if c_imps > 0 else 0.0

            r_vals = [
                c_name,
                f"₹{c_spend:,.2f}",
                f"{c_imps:,}",
                f"{c_clks:,}",
                f"{c_ctr * 100:.2f}%",
                f"₹{c_cpc:.2f}",
                f"₹{c_cpm:.2f}",
                f"{c_eng:,}",
                f"{int(c_conv)}"
            ]
            for col_idx, v in enumerate(r_vals, start=1):
                cell = ws_sum.cell(row=c_idx, column=col_idx, value=v)
                cell.font = font_regular
                cell.alignment = align_left if col_idx == 1 else align_right
                cell.border = thin_border

        # ==============================================================
        # TAB 2: Notes & Lineage
        # ==============================================================
        ws_notes = wb.create_sheet(title="Notes")
        ws_notes.views.sheetView[0].showGridLines = True

        ws_notes["A1"] = f"{display_name} - Paid Social Reporting Notes"
        ws_notes["A1"].font = font_title

        notes = [
            ("Reporting Period", period),
            ("Deliverable", self.spec.name),
            ("Canonical Schema", "paid_v2"),
            ("Currency", "INR"),
            ("Averaging Metric", "Ratio of sums (Total Spend / Total Clicks for CPC)"),
            ("Late-Arriving Lookback Window", "28 days (Meta Ads revision window)"),
        ]
        for n_idx, (k, v) in enumerate(notes, start=3):
            c1 = ws_notes.cell(row=n_idx, column=1, value=k)
            c1.font = font_bold
            c1.border = thin_border
            c2 = ws_notes.cell(row=n_idx, column=2, value=v)
            c2.font = font_regular
            c2.border = thin_border

        # Auto-adjust column widths
        for sheet in wb.worksheets:
            for col in sheet.columns:
                max_len = 0
                col_letter = get_column_letter(col[0].column)
                for cell in col:
                    if cell.value:
                        max_len = max(max_len, len(str(cell.value)))
                sheet.column_dimensions[col_letter].width = max(max_len + 3, 12)

        out_path = Path(out_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        final_file = out_path / f"{display_name.lower()}_paid_social_{period}.xlsx"
        wb.save(final_file)
        return [str(final_file.resolve())]
