from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict, List
import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from ..contract import Generator, GeneratorSpec, Requirement, register_generator


@register_generator
class GSCOrganicReportGenerator(Generator):
    """
    Deliverable: gsc_organic_report (v1.0.0)
    Generates branded Excel (.xlsx) report from canonical_search data.
    """
    spec = GeneratorSpec(
        name="gsc_organic_report",
        version="1.0.0",
        requires=(
            Requirement(
                domain="search",
                min_version="search_v1",
                columns=("impressions", "clicks", "ctr", "position", "is_branded", "product")
            ),
        ),
        outputs=("xlsx",),
        blocking_checks=("ctr_over_100", "negative_metrics"),
        uses_narrative=False,
    )

    def build(self, brand: Dict[str, Any], period: str, data: Dict[str, Any], out_dir: str | Path) -> List[str]:
        """
        Builds the branded Excel workbook for GSC Organic Search.
        """
        search_rows = data.get("search", [])
        if not search_rows:
            raise ValueError(f"No search data available for brand '{brand.get('brand_id')}' in period '{period}'.")

        # 1. Run Data Quality Checks
        for r in search_rows:
            ctr = getattr(r, "ctr", 0.0)
            clicks = getattr(r, "clicks", 0)
            impressions = getattr(r, "impressions", 0)
            if ctr > 1.0:
                raise ValueError(f"Data check failed: Query '{getattr(r, 'query', '')}' has CTR > 100% ({ctr * 100:.2f}%)")
            if clicks < 0 or impressions < 0:
                raise ValueError(f"Data check failed: Negative metrics found in query '{getattr(r, 'query', '')}'")

        # 2. Setup Brand Styling from Manifest
        identity = brand.get("identity", {})
        display_name = identity.get("display_name", "Brand")
        palette = identity.get("palette", ["1C2321", "4E8C2B"])
        primary_hex = palette[0].replace("#", "")
        accent_hex = palette[1].replace("#", "") if len(palette) > 1 else "4E8C2B"

        wb = openpyxl.Workbook()
        # Remove default sheet
        wb.remove(wb.active)

        # Style objects
        header_fill = PatternFill(start_color=primary_hex, end_color=primary_hex, fill_type="solid")
        accent_fill = PatternFill(start_color=accent_hex, end_color=accent_hex, fill_type="solid")
        light_gray_fill = PatternFill(start_color="F4F6F5", end_color="F4F6F5", fill_type="solid")

        font_header = Font(name="Arial", size=11, bold=True, color="FFFFFF")
        font_title = Font(name="Arial", size=14, bold=True, color="1C2321")
        font_subtitle = Font(name="Arial", size=10, italic=True, color="555555")
        font_bold = Font(name="Arial", size=10, bold=True)
        font_regular = Font(name="Arial", size=10)

        thin_side = Side(border_style="thin", color="CCCCCC")
        thin_border = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)
        align_left = Alignment(horizontal="left", vertical="center")
        align_right = Alignment(horizontal="right", vertical="center")
        align_center = Alignment(horizontal="center", vertical="center")

        # ==============================================================
        # TAB 1: Summary Dashboard
        # ==============================================================
        ws_sum = wb.create_sheet(title="Summary")
        ws_sum.views.sheetView[0].showGridLines = True

        ws_sum["A1"] = f"{display_name} - Organic Search Performance Report"
        ws_sum["A1"].font = font_title
        ws_sum["A2"] = f"Reporting Period: {period} | Generated by HOWL Platform v{self.spec.version}"
        ws_sum["A2"].font = font_subtitle

        # Compute Core Metrics
        tot_queries = len(search_rows)
        tot_impressions = sum(getattr(r, "impressions", 0) for r in search_rows)
        tot_clicks = sum(getattr(r, "clicks", 0) for r in search_rows)
        overall_ctr = (tot_clicks / tot_impressions) if tot_impressions > 0 else 0.0
        avg_pos = sum(getattr(r, "position", 0.0) for r in search_rows) / tot_queries if tot_queries > 0 else 0.0

        # KPI Cards
        kpi_headers = ["Total Queries", "Total Impressions", "Total Clicks", "Overall CTR", "Avg Position"]
        kpi_values = [tot_queries, tot_impressions, tot_clicks, f"{overall_ctr * 100:.2f}%", f"{avg_pos:.1f}"]

        for col_idx, (kh, kv) in enumerate(zip(kpi_headers, kpi_values), start=1):
            c_header = ws_sum.cell(row=4, column=col_idx, value=kh)
            c_header.fill = header_fill
            c_header.font = font_header
            c_header.alignment = align_center

            c_val = ws_sum.cell(row=5, column=col_idx, value=kv)
            c_val.font = Font(name="Arial", size=12, bold=True, color="1C2321")
            c_val.alignment = align_center
            c_val.fill = light_gray_fill
            c_val.border = thin_border

        # Branded vs Generic Summary
        ws_sum["A7"] = "Performance by Brand Classification"
        ws_sum["A7"].font = font_bold

        b_rows = [r for r in search_rows if getattr(r, "is_branded", False)]
        g_rows = [r for r in search_rows if not getattr(r, "is_branded", False)]

        b_clicks = sum(getattr(r, "clicks", 0) for r in b_rows)
        b_imps = sum(getattr(r, "impressions", 0) for r in b_rows)
        b_ctr = (b_clicks / b_imps) if b_imps > 0 else 0.0

        g_clicks = sum(getattr(r, "clicks", 0) for r in g_rows)
        g_imps = sum(getattr(r, "impressions", 0) for r in g_rows)
        g_ctr = (g_clicks / g_imps) if g_imps > 0 else 0.0

        seg_headers = ["Segment", "Queries", "Impressions", "Clicks", "CTR", "Click Share"]
        for c_idx, h in enumerate(seg_headers, start=1):
            cell = ws_sum.cell(row=8, column=c_idx, value=h)
            cell.fill = header_fill
            cell.font = font_header
            cell.alignment = align_center

        table_data = [
            ("Branded", len(b_rows), b_imps, b_clicks, f"{b_ctr*100:.2f}%", f"{(b_clicks/tot_clicks*100):.1f}%" if tot_clicks else "0%"),
            ("Non-Branded / Generic", len(g_rows), g_imps, g_clicks, f"{g_ctr*100:.2f}%", f"{(g_clicks/tot_clicks*100):.1f}%" if tot_clicks else "0%"),
            ("Total", tot_queries, tot_impressions, tot_clicks, f"{overall_ctr*100:.2f}%", "100.0%"),
        ]

        for r_offset, r_vals in enumerate(table_data, start=9):
            is_tot = (r_vals[0] == "Total")
            for c_offset, v in enumerate(r_vals, start=1):
                cell = ws_sum.cell(row=r_offset, column=c_offset, value=v)
                cell.font = font_bold if is_tot else font_regular
                cell.alignment = align_left if c_offset == 1 else align_right
                cell.border = thin_border
                if is_tot:
                    cell.fill = light_gray_fill

        # ==============================================================
        # TAB 2: Product Breakdown
        # ==============================================================
        ws_prod = wb.create_sheet(title="Product Breakdown")
        ws_prod.views.sheetView[0].showGridLines = True

        ws_prod["A1"] = f"{display_name} - Product Performance Breakdown ({period})"
        ws_prod["A1"].font = font_title

        prod_headers = ["Product", "Queries", "Impressions", "Clicks", "CTR", "Click Share"]
        for c_idx, h in enumerate(prod_headers, start=1):
            cell = ws_prod.cell(row=3, column=c_idx, value=h)
            cell.fill = header_fill
            cell.font = font_header
            cell.alignment = align_center

        # Group by product
        products_map: Dict[str, List[Any]] = {}
        for r in search_rows:
            p_name = getattr(r, "product", None) or "Unassigned / General"
            products_map.setdefault(p_name, []).append(r)

        # Sort products by clicks descending
        sorted_prods = sorted(
            products_map.items(),
            key=lambda item: sum(getattr(r, "clicks", 0) for r in item[1]),
            reverse=True
        )

        for p_idx, (p_name, p_rows) in enumerate(sorted_prods, start=4):
            p_clicks = sum(getattr(r, "clicks", 0) for r in p_rows)
            p_imps = sum(getattr(r, "impressions", 0) for r in p_rows)
            p_ctr = (p_clicks / p_imps) if p_imps > 0 else 0.0
            p_share = f"{(p_clicks / tot_clicks * 100):.1f}%" if tot_clicks > 0 else "0%"

            row_data = [p_name, len(p_rows), p_imps, p_clicks, f"{p_ctr*100:.2f}%", p_share]
            for c_offset, v in enumerate(row_data, start=1):
                cell = ws_prod.cell(row=p_idx, column=c_offset, value=v)
                cell.font = font_regular
                cell.alignment = align_left if c_offset == 1 else align_right
                cell.border = thin_border

        # ==============================================================
        # TAB 3: Top Queries
        # ==============================================================
        ws_queries = wb.create_sheet(title="Top Queries")
        ws_queries.views.sheetView[0].showGridLines = True

        ws_queries["A1"] = f"{display_name} - Top Queries Detail ({period})"
        ws_queries["A1"].font = font_title

        query_headers = ["Rank", "Query", "Clicks", "Impressions", "CTR", "Position", "Branded?", "Product", "Theme", "Tag Source"]
        for c_idx, h in enumerate(query_headers, start=1):
            cell = ws_queries.cell(row=3, column=c_idx, value=h)
            cell.fill = header_fill
            cell.font = font_header
            cell.alignment = align_center

        # Sort queries by clicks descending
        sorted_queries = sorted(search_rows, key=lambda r: getattr(r, "clicks", 0), reverse=True)

        for q_idx, r in enumerate(sorted_queries, start=1):
            row_num = q_idx + 3
            q_data = [
                q_idx,
                getattr(r, "query", ""),
                getattr(r, "clicks", 0),
                getattr(r, "impressions", 0),
                f"{(getattr(r, 'ctr', 0.0) * 100):.2f}%",
                f"{getattr(r, 'position', 0.0):.1f}",
                "Yes" if getattr(r, "is_branded", False) else "No",
                getattr(r, "product", "") or "-",
                getattr(r, "generic_theme", "") or "-",
                getattr(r, "tag_source", "") or "-",
            ]
            for c_offset, v in enumerate(q_data, start=1):
                cell = ws_queries.cell(row=row_num, column=c_offset, value=v)
                cell.font = font_regular
                cell.alignment = align_left if c_offset in (2, 8, 9, 10) else align_right
                cell.border = thin_border

        # ==============================================================
        # TAB 4: Notes & Methodology
        # ==============================================================
        ws_notes = wb.create_sheet(title="Notes")
        ws_notes.views.sheetView[0].showGridLines = True

        ws_notes["A1"] = "HOWL Platform - Methodology & Lineage Notes"
        ws_notes["A1"].font = font_title

        notes = [
            ("Reporting Period", period),
            ("Deliverable", self.spec.name),
            ("Generator Version", self.spec.version),
            ("Canonical Schema", "search_v1"),
            ("Data Source", "Google Search Console (Monthly Export)"),
            ("Averaging Method", "Ratio of sums (sum of clicks / sum of impressions)"),
            ("Classification Logic", "1. Decision Ledger -> 2. Manifest Rules & Variants -> 3. AI / Review Queue"),
            ("Review Gate Status", "All blocking items verified"),
        ]

        ws_notes.cell(row=3, column=1, value="Parameter").font = font_header
        ws_notes.cell(row=3, column=1).fill = header_fill
        ws_notes.cell(row=3, column=2, value="Detail").font = font_header
        ws_notes.cell(row=3, column=2).fill = header_fill

        for n_idx, (p_label, p_detail) in enumerate(notes, start=4):
            c1 = ws_notes.cell(row=n_idx, column=1, value=p_label)
            c1.font = font_bold
            c1.border = thin_border
            c2 = ws_notes.cell(row=n_idx, column=2, value=p_detail)
            c2.font = font_regular
            c2.border = thin_border

        # Auto-adjust column widths for all sheets
        for sheet in wb.worksheets:
            for col in sheet.columns:
                max_len = 0
                col_letter = get_column_letter(col[0].column)
                for cell in col:
                    if cell.value:
                        max_len = max(max_len, len(str(cell.value)))
                sheet.column_dimensions[col_letter].width = max(max_len + 3, 12)

        # 3. Save File
        out_path = Path(out_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        file_name = f"{display_name.lower()}_organic_search_report_{period}.xlsx"
        final_file = out_path / file_name
        wb.save(final_file)

        return [str(final_file.resolve())]
